apiVersion: apps/v1
kind: Deployment
metadata:
  name: pay-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pay-service
  template:
    metadata:
      labels:
        app: pay-service
    spec:
      containers:
        - name: pay-service
          image: brahimbtf/pay-service:1.0
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: pay-service-config
            - secretRef:
                name: pay-service-secret
